### ISSUE TITLE
Should we offer solutions in more than one language/version?

### ISSUE THREAD

**Issue by EugeneKramer** [coding-boot-camp/cs-technical-curriculum-public#1]
Should solutions be available in more than one language (e.g. C#/Java/Ruby/VBA) or in more than one version (e.g. ES5/ES6+)?

**Comment by acd37** [comment]
We are currently focusing on developing materials in JavaScript because the vast majority of students in our programs learn JavaScript. However, there are plans to offer solutions in Python in the near future in order to better support our Data students.
