### ISSUE TITLE
Algorithm Challenge - hasDouble - improvements

### ISSUE THREAD

**Issue by EugeneKramer** [coding-boot-camp/cs-technical-curriculum-public#2]
The [optimized version of the hasDouble algorithm challenge](https://github.com/coding-boot-camp/cs-technical-curriculum-public/master/algorithm-challenges/hasDouble/hasDouble_optimized.js) could be improved upon from:

```
function includesDoubleWithHashmap(array) {
    let doubles = {};

    let i = 0;

    while (i < array.length) {
        doubles[array[i]] = 'this text doesn not matter';
        if (doubles[(array[i] * 2)] || doubles[(array[i] / 2)]) {
            return true;
        }
        // console.log('doubles: ' + JSON.stringify(doubles))
        i++;
    }
    return false;
}
```
to
```
function includesDoubleWithHashmap(array) {
	let set1 = new Set(array);
        return array.some(i => (set1.has(2 * i) || set1.has(i / 2)));
}
```
A few other notes:

1. The use of the parameter name `array `is poor practice as `Array` is reserved.

2. `'this text doesn not matter';` is misspelled. And the size of the string does matter as it will occupy memory.

**Comment by acd37** [comment]
Updated to change param name to arr. 

Spelling error has been resolved.

The original format of the solution has been retained as this better fits in line with the skill-level of students graduating from the bootcamp as Set() is not part of the curriculum.
