### ISSUE TITLE
Box Model challenge - alternatives

### ISSUE THREAD

**Issue by EugeneKramer** [coding-boot-camp/cs-technical-curriculum-public#3]
The[ current box model challenge ](https://github.com/coding-boot-camp/cs-technical-curriculum-public/blob/master/box-model/README.md) focuses on floats. 

Would it be possible to incorporate modern alternatives such as flexbox and CSS grid?

**Comment by acd37** [comment]
The focus is on floats because the current curriculum does not teach flexbox and CSS grid. I do agree that it would be good to incorporate these technologies at some point into some sort of prep workshop.
